### ISSUE TITLE
Python 3.14 error: 'ForwardRef' object has no attribute 'default_parameter'

### ISSUE THREAD

**Issue by bjester** [ai-dynamo/aiperf#878]
## Observed behavior
I set up a virtualenv with `uv`, which by default used python 3.14. Invoking the tool errors with an error `AttributeError: 'ForwardRef' object has no attribute 'default_parameter'` that appears to come from a dependency that may not work with 3.14.

### Commands
```bash
$ uv venv
$ uv pip install aiperf
$ uv run aiperf profile --model 'qwen3.6-35b-a3b' \
    --streaming \
    --endpoint-type chat \
    --endpoint /v1/chat/completions \
    --url "mylocalurl:8000" \
    --concurrency 4 \
    --request-count 10
```

### Output
```
Traceback (most recent call last):
  File "/home/bjester/Projects/aiperf/.venv/bin/aiperf", line 10, in <module>
    sys.exit(app())
             ~~~^^
  File "/home/bjester/Projects/aiperf/.venv/lib/python3.14/site-packages/cyclopts/core.py", line 1939, in __call__
    command, bound, _ = self.parse_args(
                        ~~~~~~~~~~~~~~~^
        tokens,
        ^^^^^^^
        console=console,
        ^^^^^^^^^^^^^^^^
        end_of_options_delimiter=end_of_options_delimiter,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/bjester/Projects/aiperf/.venv/lib/python3.14/site-packages/cyclopts/core.py", line 1821, in parse_args
    command, bound, _, ignored, _ = self._parse_known_args(
                                    ~~~~~~~~~~~~~~~~~~~~~~^
        tokens,
        ^^^^^^^
        raise_on_unused_tokens=True,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/bjester/Projects/aiperf/.venv/lib/python3.14/site-packages/cyclopts/core.py", line 1676, in _parse_known_args
    argument_collection = command_app.assemble_argument_collection()
  File "/home/bjester/Projects/aiperf/.venv/lib/python3.14/site-packages/cyclopts/core.py", line 1538, in assemble_argument_collection
    return ArgumentCollection._from_callable(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.default_command,  # pyright: ignore
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        parse_docstring=parse_docstring,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/bjester/Projects/aiperf/.venv/lib/python3.14/site-packages/cyclopts/argument/_collection.py", line 444, in _from_callable
    iparam_argument_collection = cls._from_type(
        field_info,
    ...<9 lines>...
        _resolve_groups=_resolve_groups,
    )
  File "/home/bjester/Projects/aiperf/.venv/lib/python3.14/site-packages/cyclopts/argument/_collection.py", line 375, in _from_type
    subkey_argument_collection = cls._from_type(
        sub_field_info,
    ...<14 lines>...
        _resolve_groups=_resolve_groups,
    )
  File "/home/bjester/Projects/aiperf/.venv/lib/python3.14/site-packages/cyclopts/argument/_collection.py", line 375, in _from_type
    subkey_argument_collection = cls._from_type(
        sub_field_info,
    ...<14 lines>...
        _resolve_groups=_resolve_groups,
    )
  File "/home/bjester/Projects/aiperf/.venv/lib/python3.14/site-packages/cyclopts/argument/_collection.py", line 271, in _from_type
    cyclopts_parameters.append(group.default_parameter)
                               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ForwardRef' object has no attribute 'default_parameter'
```

## Expected behavior
The tool works with python versions 3.12 and 3.13, and so it's expected to work similarly for 3.14 according to it's python requirements definition.

As a result, one of the following would improve the user experience:
- The project has `requires-python = ">=3.10,<3.14"` to document this for end users, or
- Has updated dependency version requirements to correct the issue if possible, or
- Is updated to work correctly for all python versions `>=3.10` according to the current definition

**Comment by ajcasagrande** [comment]
Hi @bjester — thanks for the detailed report. Fix is up in #879: the root cause was an `_CLI_GROUP` private class attribute referenced inside `Annotated[..., CLIParameter(group=...)]` field metadata, which under PEP 649 deferred annotation evaluation (Python 3.14 default) becomes unresolvable to `typing.get_type_hints` and lands in cyclopts as a `ForwardRef`. Fix inlines `Groups.X` directly so resolution happens cleanly in module scope. The full unit suite passes on 3.14, and your exact reproducer command parses cleanly on a fresh 3.14.3 venv.

If you'd like to validate against the PR build before merge, on Python 3.14:

```bash
uv venv --python 3.14 && source .venv/bin/activate
uv pip install --upgrade --force-reinstall git+https://github.com/ai-dynamo/aiperf.git@ed49b39b10bd7b5b78830de959722cfbfe0cb4e9
```

Then re-run the command from your report. Appreciate the bug find.

**Comment by ajcasagrande** [comment]
Quick follow-up — after digging deeper on a fresh 3.14 venv, found that the cyclopts/`_CLI_GROUP` issue was only the most visible 3.14 incompatibility. There are further problems we won't fix in this PR:

- `uvloop 0.21.x` fails to import on 3.14 (fixed here by bumping to `>=0.22.1`).
- Under heavy parallel load, AIPerf subprocesses crash with `SIGSEGV`/`SIGABRT` inside C extensions on 3.14, and timing-sensitive tests see ~50% of target QPS. Diagnosing the offending extension is a separate task.

Decision in #879: keep all the in-aiperf fixes (the inline-`Groups.X` refactor + uvloop bump) but cap `requires-python` to `>=3.10,<3.14` so installing on 3.14 fails fast at resolution time with a clear error rather than crashing at runtime. That gives you exactly the user-experience you flagged as the first acceptable outcome in the issue.

So the test command from my earlier comment would now fail at install time on 3.14. If you'd still like to validate the underlying cyclopts fix on a 3.14 venv, install with `--no-deps` plus the new uvloop, or use `python_requires` override; otherwise the simplest validation is just on 3.10–3.13.

Apologies for the churn, and thanks again for the report — the cyclopts-scoping fix benefits everyone running 3.13 with `from __future__ import annotations` too.

**Comment by bjester** [comment]
Thanks for taking a look so quickly, @ajcasagrande! Given the related problems, I will stick with <3.14 for now, but I did test the PR and the documented issue is indeed resolved.
